#graphdb_filename: "../transitshed/backend/data/bart3.gdb"
#osmdb_filename: "../transitshed/backend/data/bart.osmdb"
#gtfsdb_filename: "../transitshed/backend/data/bart.gtfsdb"
#origin_label: "EMBR"
#origin_time: 1236303312
#cutoff: 7200

graphdb_filename: "../transitshed/backend/data/metrokc2.gdb"
osmdb_filename: "../transitshed/backend/data/metrokc.osmdb"
gtfsdb_filename: "../transitshed/backend/data/metrokc.gtfsdb"
origin_label: "69993"
origin_time: 1236303312
cutoff: 7200